### ISSUE TITLE
Permission to use your image as the default for GitLab?

### ISSUE THREAD

**Issue by schmitmd** [listx/texlive-docker#8]
Hey @listx , I've created the following Merge Request to the GitLab project for them to use your image as the default in their CI template for LaTeX.  I just wanted to get your official consent for them to use it.  Are you okay with this?

**Comment by schmitmd** [comment]
Whoops, forgot the link.  https://gitlab.com/gitlab-org/gitlab/-/merge_requests/52043

**Comment by listx** [comment]
Sure, that's fine.

**Comment by schmitmd** [comment]
Awesome. Thanks!
